@startuml activity_diagram
start
:Ввод данных регистрации;
if (Данные корректны?) then (да)
:Сохранение пользователя в базе данных;
:Отправка подтверждающего email;
else (нет)
:Вывод ошибок валидации;
endif
stop
@enduml