@startuml asd

class PaymentManager {
    -List<Payment>payments
    -registerPayment()
    -processAllPayments()
}

class Payment {
    -id : int
    -amount : double
    -paymentDate : date
    -transactionId : int
    -processPayment()
    -Payment(id,amount,paymentDate,transactionId)
}

abstract class CashPayment {
    -cashProvided : double
    -changeCalculation()
    -processPayment() : double
    -CashPayment(id,amount,paymentDate,transactionId,cashProvided)
}

abstract class CardPayment {
    -cardNumber : string
    -cardHolder : string
    -expiryDate : date
    -validation()
    -processPayment()
   - CardPayment(id,amount,paymentDate,transactionId,cardNumber,cardHolder,expiryDate)
}

PaymentManager o-- Payment
Payment <|-- CashPayment
Payment <|-- CardPayment



@enduml


