@startuml HW3.2
start
partition "Регистрация/авторизация клиента"{
split
    :Вход в существующий аккаунт;
split again
    :Регистрация нового аккаунта;
end split
:Подтверждение учетных данных клиента;
}

partition "Оформление заказа" {
:Просмотр товаров;

if (Проверка выбранного количества) then (На складе есть больше указанного)
:Кнопка "+" доступна;
else (На складе нет больше)
:Кнопка "+" недоступна;
:Pop-up "Посмотреть аналоги";
end if
:Добавление в корзину;
:Изменение количества для каждой позиции товара;
while (Количество изменено) is (Да)
if (Проверка выбранного количества) then (На складе есть больше указанного)
:Кнопка "+" доступна;
else (На складе нет больше)
:Кнопка "+" недоступна;
:Pop-up "Посмотреть аналоги";
end if
endwhile (Нет)
}


partition "Обработка заказа" { 
:Просмотр состава заказа;
:Выбор способа доставки;
:Выбор способа оплаты;
:Оформление заказа;
fork
    :Проверка платежных деталей;
    :Проведение транзакции;
        switch(Проверка оплаты)
        case (Успешная оплата)
        :Уведомление клиенту о смене статуса на "Оплачено";
        case (Недостаточно средств)
        :Уведомление клиенту о смене статуса на "Ожидает оплаты";
        stop
        case (Неверные платежные реквизиты) 
        :Уведомление клиенту о смене статуса на "Ожидает оплаты";
        stop
        case (ПЛатежная система недоступна) 
        :Уведомление клиенту о смене статуса на "Ожидает оплаты";
        stop
        endswitch
fork again
    :Отправка уведомления на комплектацию заказа;
    :Комплектация заказа;
    :Смена статуса на "Готово к отправке";
end fork
:Генерация счет-фактуры;
:Уведомление клиенту о готовности заказа к отправке;
:Передача в службу доставки;
:Смена статуса на "Отправлено";
:Параллельная обработка;
}

:Параллельная обработка;
stop
@enduml